version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
    plugins = ["react"]
    skip_doc_coverage = ["class-expression", "method-definition"]

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["bootstrap/app.php"]

[[transformers]]
name = "prettier"